title: JAXSR Documentation
author: John Kitchin
logo: ""

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/jkitchin/jaxsr
  branch: main

html:
  use_repository_button: true

launch_buttons:
  repository_url: https://github.com/jkitchin/jaxsr

sphinx:
  extra_extensions:
    - sphinx_copybutton
